name: "Run build"
on:
  workflow_dispatch:
  push:
    branches:
      - master
  workflow_run:
    workflows: ["Test Workflow"]
    types:
      - completed
jobs:
  debug_build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: "Set up Python"
        uses: actions/setup-python@v5

      - name: Install uv
        uses: astral-sh/setup-uv@v3
        with:
          enable-cache: true

      - name: Build fastanime
        run: uv build

      - name: Generate build report
        run: |
          echo "## Build Report" > dist/build_report.md
          echo "" >> dist/build_report.md
          echo "**Timestamp:** $(date)" >> dist/build_report.md
          echo "**Commit SHA:** ${GITHUB_SHA}" >> dist/build_report.md
          echo "**Workflow Run:** ${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}/actions/runs/${GITHUB_RUN_ID}" >> dist/build_report.md
          echo "**Python Version:** $(python --version)" >> dist/build_report.md
          echo "**uv Version:** $(uv --version)" >> dist/build_report.md
          echo "" >> dist/build_report.md
          echo "### Built artifacts:" >> dist/build_report.md
          ls -lh dist >> dist/build_report.md
          echo "" >> dist/build_report.md
          echo "### Checksums (SHA256):" >> dist/build_report.md
          cd dist
          sha256sum * >> build_report.md
          cd ..
        shell: bash # Ensure bash is used for commands like sha256sum

      - name: Archive production artifacts
        uses: actions/upload-artifact@v4
        with:
          name: fastanime_debug_build
          path: |
            dist
            build_report.md